name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            python-version: [ "3.9", "3.10", "3.11", "3.12" ]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: python
        uses: actions/setup-python@v2
        with:
            python-version: ${{ matrix.python-version }}

      - name: requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
          pip install -r requirements.txt

      - name: test
        run: |
          pytest

      - name: report
        run: |
          codecov
